# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dating' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dating

   pod 'GoogleSignIn'


  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

    pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

    pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'RCTAnimation',
    'RCTActionSheet',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTPushNotification',
    'RCTCameraRoll',
    'RCTBlob',
    'RCTGeolocation',
    'DevSupport'
  ]
  
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'ReactNativePermissions',:path => '../node_modules/react-native-permissions'
  pod 'FBSDKCoreKit', '~> 4.39.1'
  pod 'FBSDKLoginKit', '~> 4.39.1'
  pod 'FBSDKShareKit', '~> 4.39.1'
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  target 'DatingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
if target.name == "yoga"
      target.remove_from_project
    end
  end
end

